ALTER TABLE stocks ADD COLUMN IF NOT EXISTS previous_close DECIMAL(12,4) DEFAULT 0;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS change_pct DECIMAL(6,4) DEFAULT 0;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS country VARCHAR(50) DEFAULT 'US';

ALTER TABLE price_history ADD COLUMN IF NOT EXISTS open DECIMAL(12,4);
ALTER TABLE price_history ADD COLUMN IF NOT EXISTS high DECIMAL(12,4);
ALTER TABLE price_history ADD COLUMN IF NOT EXISTS low DECIMAL(12,4);
ALTER TABLE price_history ADD COLUMN IF NOT EXISTS volume BIGINT;
ALTER TABLE price_history ALTER COLUMN recorded_at TYPE DATE USING recorded_at::DATE;
