ALTER TABLE users ADD COLUMN IF NOT EXISTS security_question_1 VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS security_answer_1 VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS security_question_2 VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS security_answer_2 VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token_hash VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token_expires_at TIMESTAMP WITH TIME ZONE;
